import { groq } from 'next-sanity'

export const productsGroqQuery = groq`
{
    "pierscionki":*[_type == "pierscionki"]{
      Opis,
        _id,
        title,
        category,
        cena,
        image,
        slug,
        "details":{
          nr_wzoru,
            marka,
            kolekcja,
            kamien,
            liczba_diamentow,
            masa_diamentow,
            surowiec,
            proba,
        }
    },
    
    "kolczyki": *[_type == "kolczyki"]{
        Opis,
          _id,
        title,
        category,
        cena,
        image,
        slug,
        "details": {
          nr_wzoru,
            marka,
            kolekcja,
            surowiec,
            proba,
            szerokosc,
            dlugosc
        },
      },
    "naszyjniki": *[_type == "naszyjniki"]{
          Opis,
          _id,
        title,
        category,
        cena,
        image,
        slug,
        "details": {
          nr_wzoru,
            marka,
            kolekcja,
            surowiec,
            proba,
        },
    },
      "beads": *[_type == "beads"]{
          Opis,
          _id,
        title,
        category,
        cena,
        image,
        slug,
        "details": {
          nr_wzoru,
            marka,
            kolekcja,
            kamien,
            surowiec,
            proba,
            dlugosc,
        },
    },
      "charms": *[_type == "charms"]{
          Opis,
          _id,
        title,
        category,
        cena,
        image,
        slug,
        "details": {
          nr_wzoru,
            marka,
            kolekcja,
            surowiec,
            proba,
            dlugosc
        },
    },
      "zawieszki": *[_type == "zawieszki"]{
          Opis,
          _id,
        title,
        category,
        cena,
        image,
        slug,
        "details": {
          nr_wzoru,
            marka,
            kolekcja,
            surowiec,
            proba,
            dlugosc,
            srednica
        },
    },
      "bransoletki": *[_type == "bransoletki"]{
          Opis,
          _id,
        title,
        category,
        cena,
        image,
        slug,
        "details": {
          nr_wzoru,
            marka,
            kolekcja,
            surowiec,
            proba,
            szerokosc,
        },
    },
      "zegarki": *[_type == "zegarki"]{
          Opis,
          _id,
        title,
        category,
        cena,
        image,
        slug,
        "details": {
          nr_wzoru,
            marka,
            kolekcja,
            mechanizm,
            kaliber,
            rodzaj_koperty,
            wymiary_koperty,
            szklo,
            pasek,
            zapiecie,
            wodoszczelnosc,
            gwarancja_producenta
        },
    },
  }
`
